/* Default property templates for each component type.
   When a component is dropped onto the canvas, these provide
   the initial size, style, and content. */

export const COMPONENT_DEFAULTS = {
  div: {
    label: 'Container',
    category: 'layout',
    icon: '▢',
    defaultProps: { text: '' },
    defaultStyle: {
      width: 300,
      height: 200,
      backgroundColor: 'rgba(255,255,255,0.05)',
      border: '1px dashed rgba(255,255,255,0.15)',
      borderRadius: '8px',
    },
  },
  section: {
    label: 'Section',
    category: 'layout',
    icon: '▭',
    defaultProps: { text: '' },
    defaultStyle: {
      width: 600,
      height: 300,
      backgroundColor: 'rgba(255,255,255,0.02)',
      border: '1px solid rgba(255,255,255,0.08)',
      borderRadius: '0px',
    },
  },
  heading: {
    label: 'Heading',
    category: 'typography',
    icon: 'H',
    defaultProps: { text: 'Heading', level: 1 },
    defaultStyle: {
      width: 300,
      height: 48,
      fontSize: '32px',
      fontWeight: '700',
      color: '#f1f5f9',
    },
  },
  paragraph: {
    label: 'Paragraph',
    category: 'typography',
    icon: '¶',
    defaultProps: { text: 'Type your paragraph text here. Double-click to edit.' },
    defaultStyle: {
      width: 350,
      height: 60,
      fontSize: '14px',
      fontWeight: '400',
      color: '#94a3b8',
      lineHeight: '1.6',
    },
  },
  span: {
    label: 'Text',
    category: 'typography',
    icon: 'T',
    defaultProps: { text: 'Text' },
    defaultStyle: {
      width: 80,
      height: 24,
      fontSize: '14px',
      color: '#f1f5f9',
    },
  },
  link: {
    label: 'Link',
    category: 'typography',
    icon: '🔗',
    defaultProps: { text: 'Click me', href: '#' },
    defaultStyle: {
      width: 100,
      height: 24,
      fontSize: '14px',
      color: '#818cf8',
      textDecoration: 'underline',
      cursor: 'pointer',
    },
  },
  button: {
    label: 'Button',
    category: 'interactive',
    icon: '⬜',
    defaultProps: { text: 'Button' },
    defaultStyle: {
      width: 140,
      height: 42,
      backgroundColor: '#6366f1',
      color: '#ffffff',
      fontSize: '14px',
      fontWeight: '600',
      borderRadius: '8px',
      border: 'none',
      cursor: 'pointer',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
    },
  },
  input: {
    label: 'Text Input',
    category: 'interactive',
    icon: '⌨',
    defaultProps: { placeholder: 'Enter text...', text: '' },
    defaultStyle: {
      width: 220,
      height: 40,
      backgroundColor: '#1e293b',
      color: '#f1f5f9',
      fontSize: '14px',
      borderRadius: '6px',
      border: '1px solid rgba(255,255,255,0.15)',
      padding: '0 12px',
    },
  },
  textarea: {
    label: 'Textarea',
    category: 'interactive',
    icon: '📝',
    defaultProps: { placeholder: 'Enter long text...', text: '' },
    defaultStyle: {
      width: 280,
      height: 100,
      backgroundColor: '#1e293b',
      color: '#f1f5f9',
      fontSize: '14px',
      borderRadius: '6px',
      border: '1px solid rgba(255,255,255,0.15)',
      padding: '8px 12px',
    },
  },
  select: {
    label: 'Dropdown',
    category: 'interactive',
    icon: '▼',
    defaultProps: { text: 'Select...', options: ['Option 1', 'Option 2', 'Option 3'] },
    defaultStyle: {
      width: 200,
      height: 40,
      backgroundColor: '#1e293b',
      color: '#f1f5f9',
      fontSize: '14px',
      borderRadius: '6px',
      border: '1px solid rgba(255,255,255,0.15)',
      padding: '0 12px',
    },
  },
  image: {
    label: 'Image',
    category: 'media',
    icon: '🖼',
    defaultProps: { src: '', alt: 'Image' },
    defaultStyle: {
      width: 200,
      height: 150,
      backgroundColor: '#1e293b',
      borderRadius: '8px',
      border: '1px solid rgba(255,255,255,0.08)',
      objectFit: 'cover',
    },
  },
  navbar: {
    label: 'Navbar',
    category: 'prebuilt',
    icon: '☰',
    defaultProps: { text: 'Brand', links: ['Home', 'About', 'Contact'] },
    defaultStyle: {
      width: 800,
      height: 60,
      backgroundColor: '#111118',
      borderRadius: '0px',
      border: '1px solid rgba(255,255,255,0.08)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: '0 24px',
    },
  },
  card: {
    label: 'Card',
    category: 'prebuilt',
    icon: '🃏',
    defaultProps: { text: 'Card Title' },
    defaultStyle: {
      width: 280,
      height: 200,
      backgroundColor: '#1a1a24',
      borderRadius: '12px',
      border: '1px solid rgba(255,255,255,0.08)',
      padding: '20px',
      boxShadow: '0 4px 12px rgba(0,0,0,0.3)',
    },
  },
};

/* Category metadata for the palette sidebar */
export const CATEGORIES = [
  { id: 'layout', label: 'Layout', icon: '⊞' },
  { id: 'typography', label: 'Typography', icon: 'Aa' },
  { id: 'interactive', label: 'Interactive', icon: '☝' },
  { id: 'media', label: 'Media', icon: '◻' },
  { id: 'prebuilt', label: 'Pre-built', icon: '★' },
];

/* Style property groups for the properties panel */
export const STYLE_GROUPS = {
  layout: ['width', 'height'],
  spacing: ['padding', 'margin'],
  typography: ['fontSize', 'fontWeight', 'color', 'lineHeight', 'textAlign', 'letterSpacing'],
  background: ['backgroundColor', 'backgroundImage'],
  border: ['border', 'borderRadius', 'borderColor', 'borderWidth', 'borderStyle'],
  effects: ['opacity', 'boxShadow', 'cursor'],
};
